#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

products_list:
  path: /api/products
  controller: App\Controller\ProductController::list
  methods: [GET]


users_list:
  path: /api/users
  controller: App\Controller\UserController::list
  methods: [GET]


user_details:
  path: /api/users/{userId}
  controller: App\Controller\UserController::details
  methods: [GET]
  requirements:
    userId: '\d+'

user_create:
  path: /api/users
  controller: App\Controller\UserController::create
  methods: [POST]

user_delete:
  path: /api/users/{userId}
  controller: App\Controller\UserController::delete
  methods: [DELETE]
  requirements:
    customerId: '\d+'
    userId: '\d+'

user_update:
  path: /api/users/{userId}
  controller: App\Controller\UserController::update
  methods: [PATCH]
  requirements:
    userId: '\d+'
