#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

products_list:
  path: /api/products
  controller: App\Controller\ProductController::list
  methods: [GET]


users_list:
  path: /api/customers/{customerId}/users
  controller: App\Controller\UserController::list
  methods: [GET]
  requirements:
    customerId: '\d+'


users_details:
  path: /api/customers/{customerId}/users/{userId}/details
  controller: App\Controller\UserController::details
  methods: [GET]
  requirements:
    customerId: '\d+'
    userId: '\d+'

user_create:
  path: /api/customers/{customerId}/user/create
  controller: App\Controller\UserController::create
  methods: [POST]

users_delete:
  path: /api/customers/{customerId}/user/{userId}
  controller: App\Controller\UserController::delete
  methods: [DELETE]
  requirements:
    customerId: '\d+'
    userId: '\d+'

user_update:
  path: /api/customers/{customerId}/user/{userId}
  controller: App\Controller\UserController::update
  methods: [PATCH]
  requirements:
    customerId: '\d+'
    userId: '\d+'
